"use client"
import { useEffect } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { RouterPath } from './shared/constants/routing'
import { useRouter } from 'next/navigation'
import { SidebarProvider } from './context/sidebarcontext'
import Appconfig from './layout/appconfig'
import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "/node_modules/primeflex/primeflex.css";
import "../app/styles/layout/layout.scss"
import "../app/styles/demo/demos.scss"
const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({children}: {children: React.ReactNode}) => {
  const router = useRouter();
  useEffect(()=> {
    router.push(RouterPath.MAIN);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
          <SidebarProvider>
            <Appconfig>{children}</Appconfig>
          </SidebarProvider>
      </body>
    </html>
  )
}
export default RootLayout;